package rules

import com.example.demo.entry.Order;
import com.example.demo.entry.Contract;

/*
根据订单金额创建不同的优惠规则
*/

rule "rule_1"
when
    $order:Order(originalPrice < 100)
then
    $order.setRealPrice($order.getOriginalPrice());
    System.out.println("rule_1: 没有优惠");
end

rule "rule_2"
when
    $order:Order(originalPrice >= 100 && originalPrice < 200)
then
    $order.setRealPrice($order.getOriginalPrice() - 20);
    System.out.println("rule_2: 优惠20");
end

rule "rule_3"
when
    $order:Order(originalPrice >= 200 && originalPrice < 300)
then
    $order.setRealPrice($order.getOriginalPrice() - 50);
    System.out.println("rule_3: 优惠50");
end

/*
rule "rule_4"
when $order:Order(originalPrice >= 300)
     resultParam: Contract()
then
    //$order.setRealPrice($order.getOriginalPrice());
    resultParam.setName("z121");
    resultParam.setAge(33);
    System.out.println("rule_4: 优惠100");
end*/
